# ruff: noqa: E501
"""Gemini panel audit — ADR-020 v3 textbook ingest rewrite.

Multi-agent panel step 3 of 5:
  1. Claude drafted ADR-020
  2. Codex (GPT-5) audit ✅ (saved to 2026-05-06-codex-adr-020-audit.md)
  3. Gemini multimodal lens audit ← THIS SCRIPT
  4. Claude integrates 3-way audit
  5. 修修 final sign-off

Run: .venv/Scripts/python docs/research/2026-05-06-gemini-adr-020-audit-dispatch.py

Output: prints Gemini audit to stdout. Capture with `> file.md` if needed.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(REPO_ROOT / ".env")

from shared.gemini_client import ask_gemini  # noqa: E402

ADR_020 = (REPO_ROOT / "docs/decisions/ADR-020-textbook-ingest-v3-rewrite.md").read_text(
    encoding="utf-8"
)
CODEX_AUDIT = (REPO_ROOT / "docs/research/2026-05-06-codex-adr-020-audit.md").read_text(
    encoding="utf-8"
)

SYSTEM = (
    "You are an independent third-party auditor providing a second opinion on an ADR. "
    "The owner has explicitly asked for push-back from your unique perspective as a Gemini "
    "model — do NOT rubber-stamp existing analyses. Your value is your different viewpoint: "
    "stronger multimodal grounding, broader multilingual recall, and a different reasoning "
    "chain than Claude or GPT-5. Be concrete, cite specifics, and disagree where appropriate."
)

PROMPT = f"""# Gemini Panel Audit — ADR-020 Textbook Ingest v3 Rewrite

You are the THIRD reviewer in a multi-agent panel. Claude drafted ADR-020. Codex (GPT-5) audited it. Now you audit both — adding a Gemini-specific perspective.

## Background

Repository: Nakama (Health & Wellness AI agent system, Taiwan-based content creator).

Crisis discovered 2026-05-06: KB Concept corpus has 622 pages of which 544 (87.5%) are stub placeholders auto-generated by phase-b-reconciliation. The owner (修修) lost trust in Claude's existing pipeline design and demanded a v3 rewrite (this is ADR-020).

Owner's top priority: 品質 (quality) > 速度 (speed) > 成本 (cost). Other constraints:
- Owner is Taiwan-based, Traditional Chinese vault, English textbooks (Sport Nutrition 4E, Biochemistry of Sport & Exercise)
- KB is internal/private, feeds (1) owner's hand-written atomic content, (2) AI agent RAG synthesis for public output (transformed)
- Owner endorsed verbatim source body content based on §51 Taiwan copyright law personal-use carve-out
- Existing implementation `shared/kb_writer.upsert_concept_page` (line 591-786) implements 4-action dispatcher; ADR-016 parallel pipeline bypasses it (root cause of stub crisis)

## What you should produce

A 1500-2500 word audit in 6 sections. Focus on what's UNIQUELY valuable from Gemini perspective. Where you agree with Claude or Codex, acknowledge briefly and move on. Where you have additional insight or disagree, dig in.

### Section 1 — MULTIMODAL ASSESSMENT
- Does ADR-020's Vision triage scheme (data-rich / caption-rich / decorative) make sense?
- For textbook EPUBs specifically, what multimodal pitfalls have you seen in your training corpus that ADR-020 should address but doesn't?
- Are there figure types Claude and Codex missed?
- Verdict on Vision triage: keep / refine / reject. Specific changes if refine.

### Section 2 — RAG & EMBEDDING STRATEGY
- ADR-020 commits to "verbatim body + LLM wrapper" with chunking strategy left as "implementation detail."
- Codex pushed back on RAG quality; owner defended verbatim with "chunking can solve."
- From RAG research literature (e.g. published work on textbook-scale corpora, hybrid retrieval, semantic chunking, contextual retrieval, BGE-M3, reranker patterns): what concrete chunking + embedding + retrieval strategy should ADR-020 specify?
- What chunk size, overlap, embedding model, reranker, query expansion should be defaulted? Justify.

### Section 3 — MULTILINGUAL CONSIDERATIONS
- ADR-020 mixes English textbook source + Traditional Chinese wikilink concept names (e.g. `[[腸道菌群]]`, `[[微絨毛]]`).
- What multilingual retrieval pitfalls would you flag?
- Specific concerns: cross-lingual embedding accuracy (English text retrieving for Chinese query), bilingual concept disambiguation, term mapping pollution between English textbook terms and Chinese wikilinks
- Concrete recommendation: should ADR-020 specify bilingual term mapping discipline at concept page level?

### Section 4 — CLAUDE/CODEX BLIND SPOTS
- Where do Claude (drafter) and Codex (auditor) likely share the same bias?
- What did both miss?
- Use specific evidence from ADR-020 text or Codex audit content. Don't say "they might miss X" — say "they both missed X, here's where in the text."

### Section 5 — PROMOTION THRESHOLD CRITIQUE
- ADR-020 §Phase 3 proposes "promote concept when ≥2 sources OR single-source high-value" as the fix for the 622-stub explosion.
- Does this threshold actually solve the problem?
- Pitfalls to consider:
  - Concepts critical but only in 1 chapter (e.g. niche enzyme that's important but only in one biochem chapter)
  - Concepts that appear superficially in 2 sources but are NOT the same concept (English textbook "creatine" vs Chinese pop-sci "creatine = energy booster")
  - Threshold gaming if owner re-ingests the same source twice
  - When does "high-value single-source" qualify? Quantifiable rule needed?
- Concrete recommendation: keep threshold / refine threshold / replace with different mechanism

### Section 6 — FINAL VERDICT
- Should ADR-020 be approved as-is? Modified? Rejected?
- If modified: top 3 specific changes with reasoning. Cite ADR-020 sections.
- If rejected: what's the alternative architecture you'd propose?

## Required output style
- English (matches Codex audit, helps panel comparison)
- Concrete and specific. Cite ADR-020 sections by name (e.g. "§Phase 1", "§Considered Options C") and Codex audit by section number (e.g. "Codex §3").
- Push back where you disagree. Do not hedge with "consider exploring" — say "do X, here's why."
- This will be read by 修修 directly to make the final call.

## Codex (GPT-5) audit verbatim

{CODEX_AUDIT}

## ADR-020 full text

{ADR_020}

---

Begin your 6-section Gemini audit now."""


def main() -> int:
    print("=== Gemini panel audit dispatch ===", file=sys.stderr)
    print(f"Prompt size: {len(PROMPT)} chars (~{len(PROMPT) // 4} tokens)", file=sys.stderr)
    print("Model: gemini-2.5-pro", file=sys.stderr)
    print("Max output: 8192, thinking budget: 2048", file=sys.stderr)
    print("---", file=sys.stderr)

    response = ask_gemini(
        PROMPT,
        system=SYSTEM,
        model="gemini-2.5-pro",
        max_tokens=8192,
        thinking_budget=2048,
        temperature=0.3,
    )

    print(response)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
