#!/usr/bin/env bash
# One-shot boot of the WP staging stack for E2E tests.
#
# Usage (from repo root):
#   bash tests/fixtures/wp_staging/run.sh
#
# What this does:
#   1. docker compose up -d --wait  (waits for healthchecks)
#   2. docker compose exec wp bash /seed.sh  (installs SEOPress, creates user)
#   3. Extracts the generated app password from seed output
#   4. Writes/overwrites .env.test at repo root with the four WP_SHOSHO_* keys
#
# Safe to re-run: seed.sh's WP install / role / user / posts steps are
# internally idempotent. App passwords accumulate (seed.sh calls
# create_new_application_password() with a fresh app_id each run, so old
# rows stay in the WP DB harmlessly); .env.test always carries the latest.
#
# After this script succeeds:
#   set -a && source .env.test && set +a
#   pytest -m live_wp tests/e2e/
#
# Teardown:
#   docker compose -f tests/fixtures/wp_staging/docker-compose.yml down -v

set -euo pipefail

COMPOSE_FILE="tests/fixtures/wp_staging/docker-compose.yml"
ENV_TEST_FILE=".env.test"

if [[ ! -f "$COMPOSE_FILE" ]]; then
    echo "ERROR: $COMPOSE_FILE not found. Run this from the repo root." >&2
    exit 1
fi

echo "==> Starting WP staging stack (may take ~60s on cold boot)..."
docker compose -f "$COMPOSE_FILE" up -d --wait

echo "==> Running seed.sh inside wp container..."
SEED_LOG=$(mktemp)
trap 'rm -f "$SEED_LOG"' EXIT
docker compose -f "$COMPOSE_FILE" exec -T wp bash /seed.sh | tee "$SEED_LOG"

APP_PASS=$(grep -oE 'Application password: [^ ]+' "$SEED_LOG" | head -1 | awk '{print $3}')
if [[ -z "${APP_PASS:-}" ]]; then
    echo "ERROR: could not parse app password from seed output. See full log above." >&2
    exit 2
fi

cat > "$ENV_TEST_FILE" <<EOF
# Generated by tests/fixtures/wp_staging/run.sh — safe to regenerate.
# Points WordPressClient.from_env('wp_shosho') at the local Docker stack.
WP_SHOSHO_BASE_URL=http://localhost:8888
WP_SHOSHO_USERNAME=nakama_publisher
WP_SHOSHO_APP_PASSWORD=$APP_PASS
PYTEST_WP_BASE_URL=http://localhost:8888
EOF

echo ""
echo "==> Wrote $ENV_TEST_FILE"
echo ""
echo "Next:"
echo "    set -a && source $ENV_TEST_FILE && set +a"
echo "    pytest -m live_wp tests/e2e/"
